# ===============================
# = POSTGRESQL DATABASE
# ===============================
# Change the values below to match your PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_list
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
# create-drop: drops the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
# create: creates the schema, destroying previous data.
# update: updates the schema.
# validate: validates the schema, makes no changes to the database.
spring.jpa.hibernate.ddl-auto=update

# This property is used to show the SQL queries in the console
spring.jpa.show-sql=true

# ===============================
# = APPLICATION
# ===============================
spring.application.name=to-do-list
