spring.application.name=to-do-list

# Configuracoes do DataSource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_list
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuracoes do JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Esta linha faz com que o Hibernate crie as tabelas automaticamente a partir das suas entidades
spring.jpa.hibernate.ddl-auto=update
